### ISSUE TITLE
Failed precondition: Attempting to use uninitialized value spectral_net_learning_rate

### ISSUE THREAD

**Issue by zylscience** [hi-zhenyu/MvSCN#1]
Hello, I want to reproduce the results in this paper but I failed. When I ran this code on Ubuntu 16.04 + Tensorflow 1.15 + keras 2.3.1,  the following error happened:
******************************************************************************************
(0) Failed precondition: Attempting to use uninitialized value spectral_net_learning_rate
	 [[{{node spectral_net_learning_rate/read}}]]
	 [[Reshape_20/_1781]]
  (1) Failed precondition: Attempting to use uninitialized value spectral_net_learning_rate
	 [[{{node spectral_net_learning_rate/read}}]]
0 successful operations.
0 derived errors ignored.
*******************************************************************************************

Then, I change the code in the class MvSCN (network.py):
K.get_session().run(tf.initialize_all_variables())

The code ran successfully, but I only get the poor results on Caltech101-20:
ACC:0.2994, NMI:0.4467

So how do I get the correct results? Thank you.

**Comment by hi-zhenyu** [comment]
Solved by changing the environment to:

Ubuntu 16.04 + cuda 9.0
tensorflow1.9.0 
keras 2.1.6
